---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-operator
  namespace: default
  labels:
    app: ollama-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-operator
  template:
    metadata:
      labels:
        app: ollama-operator
    spec:
      serviceAccountName: ollama-operator
      containers:
      - name: operator
        image: webcodes0071/ollama-operator:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: KOPF_NAMESPACE
          value: default
        - name: PYTHONUNBUFFERED
          value: "1"
        # Remove health probes since kopf operator doesn't expose health endpoints by default
        # We'll rely on pod status instead
        # ports:
        # - containerPort: 11434
        #   name: http
        # readinessProbe:
        #   tcpSocket:
        #     port: 11434
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 11434
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ollama-operator
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "watch", "patch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]

- apiGroups: ["example.com"]
  resources: ["ollamamodels"]
  verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]

- apiGroups: ["example.com"]
  resources: ["ollamamodels/status"]
  verbs: ["get", "patch", "update"]

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-operator
subjects:
- kind: ServiceAccount
  name: ollama-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: ollama-operator
  apiGroup: rbac.authorization.k8s.io