apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ollamamodels.example.com
spec:
  group: example.com
  names:
    kind: OllamaModel
    plural: ollamamodels
    singular: ollamamodel
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["modelName"]
              properties:
                modelName:
                  type: string
                image:
                  type: string
                probes:
                  type: object
                  properties:
                    readiness:
                      type: object
                      properties:
                        initialDelaySeconds:
                          type: integer
                        periodSeconds:
                          type: integer
                    liveness:
                      type: object
                      properties:
                        initialDelaySeconds:
                          type: integer
                        periodSeconds:
                          type: integer
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                volumeMounts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                replicas:
                  type: integer
                  minimum: 1
                serviceType:
                  type: string
                  enum: ["ClusterIP", "NodePort", "LoadBalancer"]
            status:
              type: object
              properties:
                phase:
                  type: string
                ready:
                  type: boolean
                pod_name:
                  type: string
                model:
                  type: string
                error:
                  type: string
                created_at:
                  type: string
                last_updated:
                  type: string
                last_error_time:
                  type: string
      additionalPrinterColumns:
        - name: Model
          type: string
          jsonPath: .spec.modelName
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Ready
          type: boolean
          jsonPath: .status.ready
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
