---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-operator
  template:
    metadata:
      labels:
        app: ollama-operator
    spec:
      serviceAccountName: ollama-operator
      containers:
      - name: operator
        image: webcodes0071/ollama-operator:v2
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: "1Gi" 
          requests: 
            cpu: "250m"   
            memory: "256Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ollama-operator
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "watch", "patch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]

- apiGroups: ["example.com"]
  resources: ["ollamamodels"]
  verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]

- apiGroups: ["example.com"]
  resources: ["ollamamodels/status"]
  verbs: ["get", "patch", "update"]

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-operator
subjects:
- kind: ServiceAccount
  name: ollama-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: ollama-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama-service
    model: mistral
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434